<?php

return [
    'roles' => [
        'admin' => ['*'],
        'sales' => [
            'app.access',
            'dashboard.view',
            'api.access',
            'products.view',
            'customers.view',
            'orders.view',
            'orders.create',
            'orders.update',
            'orders.confirm',
            'orders.complete',
            'orders.cancel',
            'orders.return',
            'invoices.view',
        ],
        'warehouse' => [
            'app.access',
            'dashboard.view',
            'products.view',
            'inventory.view',
            'inventory.adjust',
            'inventory.transfer',
            'orders.view',
            'orders.ship',
            'purchase_orders.view',
            'purchase_orders.receive',
        ],
        'finance' => [
            'app.access',
            'dashboard.view',
            'api.access',
            'finance.view',
            'accounts.view',
            'accounts.manage',
            'journal_entries.view',
            'journal_entries.reverse',
            'accounting_periods.view',
            'accounting_periods.manage',
            'invoices.view',
            'payments.record',
            'purchase_orders.view',
        ],
    ],
];
